name: sx_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter
  # 网络请求
  dio: ^3.0.10
  # 状态管理
  provider: ^4.3.2
  cupertino_icons: ^0.1.3
  # 下拉刷新，上拉加载
  pull_to_refresh: ^1.6.1
  # 轮播
  flutter_swiper: ^1.1.6
  common_utils: ^1.2.1
  video_player: ^0.10.11+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
flutter_intl:
  enabled: true
